/**
 * Claim Adjustment Reason Codes (CARC) library — the reviewed source of truth
 * for the /codes/ pages. Patient-oriented, deliberately hedged: codes arrive
 * with remark codes and plan-specific detail, so every page says "check the
 * letter" rather than promising outcomes.
 *
 * group: CO = contractual obligation (in-network providers generally cannot
 * bill the member for CO adjustments), PR = patient responsibility,
 * OA = other adjustment.
 * fix: who usually resolves it — "provider" (billing office), "patient", "both".
 * appeal: "yes" | "sometimes" | "rarely".
 * guide: related /appeals/ slug ("" when none fits).
 */
export const codes = [
  { code: "CO-4", slug: "co-4", group: "CO", fix: "provider", appeal: "rarely",
    name: "Procedure code inconsistent with the modifier",
    meaning: "The billing office used a procedure code and modifier combination the payer considers invalid. This is a coding problem on the claim, not a judgment about your care.",
    steps: ["Call the provider's billing office and ask them to correct the code/modifier and resubmit.", "Nothing is owed by you while a corrected claim is pending — ask the office to confirm.", "If a corrected claim is denied again, ask the office whether an appeal with records is warranted."],
    guide: "" },
  { code: "CO-11", slug: "co-11", group: "CO", fix: "provider", appeal: "rarely",
    name: "Diagnosis inconsistent with the procedure",
    meaning: "The payer says the diagnosis code on the claim doesn't support the billed procedure. Usually a mismatch in the paperwork rather than a coverage decision.",
    steps: ["Ask the billing office to verify the diagnosis and procedure codes against your chart and resubmit.", "If the codes were right, the office can appeal with chart notes showing why the procedure fit the diagnosis."],
    guide: "" },
  { code: "CO-15", slug: "co-15", group: "CO", fix: "provider", appeal: "sometimes",
    name: "Authorization number missing or invalid",
    meaning: "Care that needed prior authorization was billed without a valid authorization number — sometimes because one was never obtained, sometimes because a valid number wasn't put on the claim.",
    steps: ["Ask the provider whether an authorization existed; if yes, they resubmit with the number.", "If authorization was never obtained, ask about a retroactive authorization request.", "If the payer refuses, appeal — especially where the service was urgent or the auth failure wasn't yours."],
    guide: "prior-authorization-denied" },
  { code: "CO-16", slug: "co-16", group: "CO", fix: "provider", appeal: "rarely",
    name: "Claim lacks information or has a submission error",
    meaning: "Something required is missing from the claim itself — an identifier, a date, an attachment. The accompanying remark codes (usually starting with M or N) say exactly what.",
    steps: ["Read the remark codes on the notice for the specific missing item.", "Ask the billing office to supply it and resubmit — this usually doesn't need a formal appeal.", "Watch the timely-filing clock: corrected claims still have deadlines."],
    guide: "" },
  { code: "CO-18", slug: "co-18", group: "CO", fix: "provider", appeal: "rarely",
    name: "Duplicate claim or service",
    meaning: "The payer believes this exact claim was already submitted. Often harmless — a resubmission crossing paths with the original.",
    steps: ["Check whether the original claim was paid; if so, nothing to do.", "If the original was actually denied or lost, the billing office should reference it and resubmit properly."],
    guide: "" },
  { code: "CO-22", slug: "co-22", group: "CO", fix: "both", appeal: "sometimes",
    name: "Care may be covered by another payer (coordination of benefits)",
    meaning: "The payer thinks another insurer should pay first — common after job changes, with two working spouses, or after accidents. The claim is parked until coordination of benefits is updated.",
    steps: ["Call your insurer and update your coordination-of-benefits information (they usually just need a short questionnaire).", "Ask the other insurer (if any) to process first, then have the claim resubmitted with that outcome.", "If there is no other coverage, say so — the claim should then process normally."],
    guide: "" },
  { code: "CO-26", slug: "co-26", group: "CO", fix: "both", appeal: "sometimes",
    name: "Expenses incurred before coverage began",
    meaning: "The payer's records say your coverage started after the date of service. Sometimes true; often an enrollment-date error.",
    steps: ["Check your coverage effective date on your ID card, enrollment letter, or HR/marketplace account.", "If the payer's date is wrong, send proof of the correct effective date and ask for reprocessing.", "If enrollment paperwork was delayed through no fault of yours, appeal with the enrollment timeline documented."],
    guide: "appeal-letter-template" },
  { code: "CO-27", slug: "co-27", group: "CO", fix: "both", appeal: "sometimes",
    name: "Expenses incurred after coverage ended",
    meaning: "The payer believes your policy had already terminated on the date of service. Frequently an eligibility-file error after job changes or plan renewals.",
    steps: ["Verify your termination date with HR, the marketplace, or the insurer's eligibility department.", "If coverage was active (including COBRA), send proof and request reprocessing.", "Appeal with the paper trail if the payer won't correct the date."],
    guide: "appeal-letter-template" },
  { code: "CO-29", slug: "co-29", group: "CO", fix: "provider", appeal: "sometimes",
    name: "Timely filing limit expired",
    meaning: "The provider submitted the claim after the payer's filing deadline. In-network, this is generally the provider's problem — network contracts usually bar billing the member for late-filed claims.",
    steps: ["Don't pay a bill for a CO-29 denial before asking questions — ask the provider's office why the claim was late.", "In-network: point out that timely-filing write-offs are typically the provider's responsibility under their contract.", "The office can appeal with proof of original timely submission if the claim was actually sent on time."],
    guide: "" },
  { code: "CO-45", slug: "co-45", group: "CO", fix: "provider", appeal: "rarely",
    name: "Charge exceeds the contracted fee schedule",
    meaning: "Not really a denial: the billed price was higher than the insurer's negotiated rate, and the difference is written off. In-network providers cannot bill you for this adjustment.",
    steps: ["Check your EOB: you owe at most your deductible/coinsurance share of the allowed amount.", "If the provider bills you for the written-off difference (in-network), dispute it — that's balance billing the contract forbids."],
    guide: "" },
  { code: "CO-50", slug: "co-50", group: "CO", fix: "patient", appeal: "yes",
    name: "Not deemed medically necessary",
    meaning: "The payer's reviewer decided the service doesn't meet their medical-necessity criteria. This is the classic appealable denial — a coverage opinion, not a medical ruling, and it is frequently overturned when the treating clinician's reasoning gets into the file.",
    steps: ["Request the specific clinical policy and the reviewer's rationale (you're entitled to both, free).", "Ask your doctor for a letter of medical necessity that answers those criteria point by point.", "File an internal appeal; if upheld, request independent external review."],
    guide: "not-medically-necessary" },
  { code: "CO-96", slug: "co-96", group: "CO", fix: "patient", appeal: "sometimes",
    name: "Non-covered charges",
    meaning: "The payer classifies the service as not covered under the plan. Sometimes a true exclusion; sometimes a miscategorization of a covered service.",
    steps: ["Find the exact exclusion in your plan documents — ask the insurer to cite the provision.", "If the service was miscategorized (e.g., preventive billed as diagnostic), ask the provider to correct the coding.", "Appeal when the plan language actually covers your situation."],
    guide: "how-to-appeal-health-insurance-denial" },
  { code: "CO-97", slug: "co-97", group: "CO", fix: "provider", appeal: "rarely",
    name: "Payment included in another billed service (bundled)",
    meaning: "The payer considers this service part of another procedure already paid — a bundling rule. A provider-side coding matter in nearly all cases.",
    steps: ["Ask the billing office to review; if the service was genuinely separate, they can rebill with the proper modifier.", "In-network, bundled write-offs are generally not billable to you."],
    guide: "" },
  { code: "CO-109", slug: "co-109", group: "CO", fix: "provider", appeal: "rarely",
    name: "Claim not covered by this payer — submit elsewhere",
    meaning: "The claim went to the wrong payer or the wrong contractor (common with plan changes, or Medicare vs. Medicare Advantage confusion).",
    steps: ["Confirm which insurer was active on the date of service and tell the billing office.", "The office resubmits to the correct payer; the wrong-payer denial itself needs no appeal."],
    guide: "" },
  { code: "CO-119", slug: "co-119", group: "CO", fix: "patient", appeal: "sometimes",
    name: "Benefit maximum reached",
    meaning: "The payer says you've used up a capped benefit (e.g., therapy visits). Caps are real, but counters are sometimes wrong — and some caps are unenforceable for essential benefits.",
    steps: ["Ask for the benefit accumulator: exactly which visits/services were counted.", "Check for counting errors (other patients' claims, duplicates, out-of-network visits counted against in-network caps).", "Appeal if the count is wrong, or if the cap conflicts with your plan documents."],
    guide: "how-to-appeal-health-insurance-denial" },
  { code: "CO-151", slug: "co-151", group: "CO", fix: "patient", appeal: "yes",
    name: "Frequency of services not supported",
    meaning: "The payer thinks you received this service too often (e.g., imaging repeated 'too soon'). Frequency rules bend to clinical reality — with documentation.",
    steps: ["Ask which frequency policy applies and what interval it expects.", "Have your doctor document why the repeat service was clinically necessary at that interval.", "Appeal with that documentation; frequency denials are regularly overturned."],
    guide: "not-medically-necessary" },
  { code: "CO-167", slug: "co-167", group: "CO", fix: "patient", appeal: "yes",
    name: "Diagnosis not covered",
    meaning: "The payer says your plan doesn't cover treatment for this diagnosis. Check both directions: whether the diagnosis code was right, and whether the exclusion is real.",
    steps: ["Verify with the provider that the diagnosis code on the claim is accurate.", "Ask the insurer to cite the exact plan exclusion.", "Appeal if the diagnosis was miscoded or the plan language doesn't actually exclude it."],
    guide: "how-to-appeal-health-insurance-denial" },
  { code: "CO-197", slug: "co-197", group: "CO", fix: "both", appeal: "yes",
    name: "Precertification / prior authorization absent",
    meaning: "The service required prior authorization and the payer has no record of one. One of the most common — and most fixable — denials.",
    steps: ["Ask the provider whether authorization was obtained; a valid number just gets resubmitted.", "If none was obtained, request retroactive authorization — payers grant it more often than people expect, especially for urgent care.", "Appeal if retro-auth is refused; authorization failures by the provider are generally not the patient's bill in-network."],
    guide: "prior-authorization-denied" },
  { code: "CO-198", slug: "co-198", group: "CO", fix: "both", appeal: "yes",
    name: "Precertification exceeded (more visits/units than authorized)",
    meaning: "Authorization existed but covered fewer visits, days, or units than were used. The overflow gets denied.",
    steps: ["Ask the provider to request an authorization extension covering the additional units.", "If care is ongoing, get the extension request in before more visits accumulate.", "Appeal denied overflow units with clinical notes showing why the extra care was needed."],
    guide: "prior-authorization-denied" },
  { code: "CO-204", slug: "co-204", group: "CO", fix: "patient", appeal: "yes",
    name: "Service not covered under the current benefit plan",
    meaning: "The payer says this service, drug, or supply simply isn't a benefit of your plan. For medications this often means a formulary exclusion — which has its own exception process.",
    steps: ["For drugs: file a formulary exception with your prescriber's support.", "For services: ask the insurer to cite the exclusion, then compare against your Evidence of Coverage.", "Appeal when the plan language covers your situation or an exception pathway applies."],
    guide: "formulary-exclusion-denial" },
  { code: "CO-231", slug: "co-231", group: "CO", fix: "provider", appeal: "rarely",
    name: "Mutually exclusive procedures",
    meaning: "Two billed procedures can't be paid together under coding rules. A provider-side coding matter.",
    steps: ["Ask the billing office to review the code pair; a corrected claim or modifier usually resolves it.", "In-network, these write-offs are generally not billable to you."],
    guide: "" },
  { code: "CO-234", slug: "co-234", group: "CO", fix: "provider", appeal: "rarely",
    name: "Procedure not paid separately",
    meaning: "The payer treats this procedure as part of another service on the claim. Like CO-97, a bundling rule.",
    steps: ["The billing office reviews whether a modifier legitimately separates the services and rebills if so.", "You generally owe nothing extra for bundled write-offs in-network."],
    guide: "" },
  { code: "CO-236", slug: "co-236", group: "CO", fix: "provider", appeal: "rarely",
    name: "Procedure/modifier combination not compatible",
    meaning: "The billed combination violates the payer's coding edits (often NCCI edits). Paperwork, not coverage.",
    steps: ["Ask the billing office to correct and resubmit.", "No patient action needed in most cases — but confirm you're not being billed for it."],
    guide: "" },
  { code: "CO-242", slug: "co-242", group: "CO", fix: "patient", appeal: "yes",
    name: "Services not provided by network providers",
    meaning: "The payer processed this as out-of-network care. Networks change and directories lag — this denial is frequently wrong or protected against.",
    steps: ["Check whether the provider was listed in-network in the payer's directory when you booked — screenshot it if still there.", "For emergencies and certain surprise out-of-network situations at in-network facilities, federal protections may apply.", "Appeal with directory evidence, or request a network-gap exception if no in-network alternative existed."],
    guide: "out-of-network-denial" },
  { code: "CO-243", slug: "co-243", group: "CO", fix: "both", appeal: "sometimes",
    name: "Services not authorized by network/primary care providers",
    meaning: "Your plan (often an HMO) required a referral or PCP authorization that isn't on file.",
    steps: ["Ask your PCP's office whether a referral was issued; if yes, have it resubmitted with the claim.", "If no referral was issued, ask about a retroactive referral — offices handle these routinely.", "Appeal when the care was urgent or a referral genuinely existed."],
    guide: "prior-authorization-denied" },
  { code: "CO-252", slug: "co-252", group: "CO", fix: "provider", appeal: "rarely",
    name: "Attachment or documentation required",
    meaning: "The payer wants supporting records before deciding — not a denial on the merits yet.",
    steps: ["Ask the billing office to send the requested documentation promptly.", "Track the claim afterward; a merits decision (and appeal rights) comes after review."],
    guide: "" },
  { code: "CO-B7", slug: "co-b7", group: "CO", fix: "provider", appeal: "rarely",
    name: "Provider not certified/eligible to be paid for this service",
    meaning: "A credentialing problem on the provider's side for this service or date. Not about your coverage.",
    steps: ["The provider's office resolves credentialing with the payer and resubmits.", "In-network, you generally can't be billed for a provider credentialing failure — push back if billed."],
    guide: "" },
  { code: "CO-B15", slug: "co-b15", group: "CO", fix: "provider", appeal: "rarely",
    name: "Required qualifying service/procedure missing",
    meaning: "The payer expected a linked service (e.g., a primary procedure) that doesn't appear on this or a related claim.",
    steps: ["The billing office checks whether the qualifying service was performed and billed correctly, then resubmits.", "If the qualifying-service rule itself is the obstacle to needed care, ask about an exception with clinical support."],
    guide: "" },
  { code: "OA-23", slug: "oa-23", group: "OA", fix: "provider", appeal: "rarely",
    name: "Impact of prior payer adjudication",
    meaning: "An informational adjustment showing how the primary insurer's payment affected this secondary claim. Usually not a denial at all.",
    steps: ["Read the EOB alongside the primary payer's EOB — the numbers should reconcile.", "Question the secondary payer if benefits you expected weren't applied."],
    guide: "" },
  { code: "PR-1", slug: "pr-1", group: "PR", fix: "patient", appeal: "rarely",
    name: "Deductible",
    meaning: "The claim was applied to your annual deductible — covered, but you pay until the deductible is met.",
    steps: ["Verify the deductible math on your EOB against your plan's accumulator (member portal).", "Check that in-network claims weren't applied to a separate out-of-network deductible.", "You still get the negotiated rate — never pay billed charges above the allowed amount."],
    guide: "" },
  { code: "PR-2", slug: "pr-2", group: "PR", fix: "patient", appeal: "rarely",
    name: "Coinsurance",
    meaning: "Your percentage share of the allowed amount after deductible. Expected cost-sharing, but worth verifying.",
    steps: ["Confirm the percentage matches your plan (e.g., 20% in-network).", "Check the out-of-pocket maximum — once reached, coinsurance should stop."],
    guide: "" },
  { code: "PR-3", slug: "pr-3", group: "PR", fix: "patient", appeal: "rarely",
    name: "Copayment",
    meaning: "The fixed per-visit amount your plan assigns. Routine — but miscategorized visits produce wrong copays.",
    steps: ["Check the visit type: specialist vs. primary vs. preventive copays differ, and preventive visits are often $0.", "Ask the provider to re-code if a preventive visit was billed as diagnostic."],
    guide: "" },
  { code: "PR-31", slug: "pr-31", group: "PR", fix: "both", appeal: "sometimes",
    name: "Patient cannot be identified as insured",
    meaning: "The payer couldn't match you to an active policy — usually a typo in the ID, name, or date of birth on the claim.",
    steps: ["Give the provider's office a photo of your current insurance card and confirm your details.", "Have the claim resubmitted with corrected identifiers.", "If you were enrolled but the payer's file is wrong, escalate to the insurer's enrollment team with proof."],
    guide: "" },
  { code: "PR-33", slug: "pr-33", group: "PR", fix: "both", appeal: "sometimes",
    name: "Insured has no dependent coverage",
    meaning: "A claim for a dependent (often a newborn) hit a policy without dependent coverage on file. Newborn enrollment windows cause most of these.",
    steps: ["Newborns: enroll within your plan's window (often 30–60 days from birth) — coverage is then generally retroactive to birth.", "Verify dependents listed on the policy and fix enrollment with HR or the marketplace.", "Appeal with the enrollment timeline if the dependent was actually covered."],
    guide: "appeal-letter-template" },
  { code: "PR-49", slug: "pr-49", group: "PR", fix: "both", appeal: "sometimes",
    name: "Routine/preventive exam not covered",
    meaning: "The payer classified the service as a routine exam outside benefits. But most plans must cover a defined set of preventive services at no cost — miscoding causes many of these denials.",
    steps: ["Check whether the service is on your plan's preventive list (most in-network preventive care is $0 under federal rules).", "If it was preventive, ask the provider to re-code and resubmit.", "Appeal if the payer still refuses a service your plan's preventive benefits cover."],
    guide: "how-to-appeal-health-insurance-denial" },
  { code: "PR-96", slug: "pr-96", group: "PR", fix: "patient", appeal: "yes",
    name: "Non-covered charges (patient responsibility)",
    meaning: "Like CO-96, but the payer is assigning the bill to you. Worth scrutiny — 'non-covered' labels are frequently wrong or appealable.",
    steps: ["Demand the exact plan provision excluding the service.", "Compare against your Evidence of Coverage; exclusions are construed from the plan document, not the payer's summary.", "Appeal with plan language and clinical documentation when the exclusion doesn't fit."],
    guide: "how-to-appeal-health-insurance-denial" },
  { code: "PR-204", slug: "pr-204", group: "PR", fix: "patient", appeal: "yes",
    name: "Service/drug not covered under the current plan (patient billed)",
    meaning: "The payer says the item isn't a plan benefit and the cost is yours. For medications, the formulary-exception process is the tool; for services, the exclusion needs verifying.",
    steps: ["Drugs: file a formulary exception with prescriber support — decisions typically come fast.", "Services: get the exclusion cited, and check your plan documents yourself.", "Appeal, and use external review if internal appeal fails — 'not covered' calls get reversed."],
    guide: "formulary-exclusion-denial" },
];
